version: "3.8"

services:
  app:
    build: ./app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=dev
      - PORT=3000
    volumes:
      # mount source code for hot reload during  development
      - ./app/src:/app/src
    networks:
      - todo-container-network
    depends_on:
      - redis

  redis:
    image: redis:latest-alpine
    ports:
      - "6379:6379"
    volumes:
      # persist redis data
      - redis-data:/data
    networks:
      - todo-container-network

volumes:
  redis-data:

networks:
  todo-container-network:
    driver: bridge
