# secret manifest  file (sensitive configuration)

apiVersion: v1
kind: Secret
metadata:
  name: microservice-secret
  namespace: microservice-ns
type: Opaque
data:
  DB_PASSWORD: admin # convert to base64
  REDIS_PASSWORD: admin # convert base64
